import React from "react";

export default function AiArchitecturePage({ navigateTo }) {
    return (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4">
            <button onClick={() => navigateTo("learningLab")} className="text-slate-400 hover:text-white mb-4 transition-colors flex items-center gap-2"><span>←</span> Back to Lab</button>
            <h2 className="text-3xl font-bold text-white">Inside the AI Pipeline</h2>
            <p className="text-slate-400">How the Neurosymbolic Engine processes an MRI scan.</p>
            <div className="space-y-8 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-slate-300 before:to-transparent">
                <div className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active"><div className="flex items-center justify-center w-10 h-10 rounded-full border border-white bg-slate-900 group-[.is-active]:bg-emerald-500 text-slate-500 group-[.is-active]:text-emerald-50 shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2">1</div><div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] bg-slate-900 p-4 rounded-xl border border-slate-700 shadow"><div className="flex items-center justify-between space-x-2 mb-1"><div className="font-bold text-slate-200">Preprocessing</div></div><div className="text-slate-400 text-sm">The raw MRI image is resized to 128x128 (for classification) and 256x256 (for segmentation), normalized to 0-1 range, and converted to grayscale if needed.</div></div></div>
                <div className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active"><div className="flex items-center justify-center w-10 h-10 rounded-full border border-white bg-slate-900 group-[.is-active]:bg-indigo-500 text-slate-500 group-[.is-active]:text-emerald-50 shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2">2</div><div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] bg-slate-900 p-4 rounded-xl border border-slate-700 shadow"><div className="flex items-center justify-between space-x-2 mb-1"><div className="font-bold text-slate-200">CNN Classification</div></div><div className="text-slate-400 text-sm">A VGG16-based Convolutional Neural Network scans features to predict the tumor type (Glioma, Meningioma, Pituitary).</div></div></div>
                <div className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active"><div className="flex items-center justify-center w-10 h-10 rounded-full border border-white bg-slate-900 group-[.is-active]:bg-purple-500 text-slate-500 group-[.is-active]:text-emerald-50 shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2">3</div><div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] bg-slate-900 p-4 rounded-xl border border-slate-700 shadow"><div className="flex items-center justify-between space-x-2 mb-1"><div className="font-bold text-slate-200">U-Net Segmentation</div></div><div className="text-slate-400 text-sm">A U-Net model generates a pixel-perfect mask of the tumor boundary, allowing for precise volume calculation.</div></div></div>
                <div className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active"><div className="flex items-center justify-center w-10 h-10 rounded-full border border-white bg-slate-900 group-[.is-active]:bg-pink-500 text-slate-500 group-[.is-active]:text-emerald-50 shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2">4</div><div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] bg-slate-900 p-4 rounded-xl border border-slate-700 shadow"><div className="flex items-center justify-between space-x-2 mb-1"><div className="font-bold text-slate-200">Neurosymbolic Reasoning</div></div><div className="text-slate-400 text-sm">The system extracts symbolic facts (volume, location) and applies medical rules (e.g., "If volume less than 1cm in pituitary - Macroadenoma") to generate the final text explanation.</div></div></div>
            </div>
        </div>
    );
}
