import React from "react";
import { TUMOR_KNOWLEDGE_BASE } from "../utils/constants";

export default function TumorLibraryPage({ navigateTo }) {
    return (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4">
            <button onClick={() => navigateTo("learningLab")} className="text-slate-400 hover:text-white mb-4 flex items-center gap-2 transition-colors"><span>←</span> Back to Lab</button>
            <div className="border-b border-slate-800 pb-4"><h2 className="text-3xl font-bold text-white">Tumor Reference Library</h2><p className="text-slate-400 mt-2">Pathology, origins, and physiological impact on the brain.</p></div>
            <div className="grid gap-8">{Object.entries(TUMOR_KNOWLEDGE_BASE).map(([type, data]) => (<div key={type} className="bg-slate-900 border border-slate-700 rounded-2xl overflow-hidden hover:border-indigo-500/50 transition-colors shadow-xl"><div className="bg-slate-800/50 p-6 border-b border-slate-700 flex flex-col md:flex-row justify-between items-start md:items-center gap-4"><div><h3 className="text-2xl font-bold text-white">{data.title}</h3><p className="text-indigo-400 text-sm font-medium mt-1">{data.origin}</p></div><span className={`px-4 py-1.5 rounded-full text-xs font-bold border ${data.severity.includes('High') ? 'bg-red-500/10 text-red-400 border-red-500/30' : data.severity.includes('Moderate') ? 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30' : 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'}`}>Severity: {data.severity}</span></div><div className="p-6 grid md:grid-cols-2 gap-8"><div className="space-y-6"><div><h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Etiology (Causes)</h4><p className="text-sm text-slate-300 leading-relaxed bg-slate-950/30 p-3 rounded-lg border border-slate-800">{data.cause}</p></div><div><h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Impact on Brain</h4><p className="text-sm text-slate-300 leading-relaxed">{data.impact}</p></div></div><div><h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-3">MRI Visual Identifiers</h4><ul className="space-y-2">{data.visualCues.map((cue, i) => (<li key={i} className="text-sm text-slate-300 flex items-start gap-3 p-2 rounded hover:bg-slate-800/50 transition-colors"><span className="text-indigo-500 mt-1">●</span><span>{cue}</span></li>))}</ul><div className="mt-6 p-3 bg-indigo-900/10 border border-indigo-500/20 rounded-lg"><p className="text-xs text-indigo-300 text-center">🤖 The AI uses these visual cues (texture, boundary) to classify this tumor type.</p></div></div></div></div>))}</div>
        </div>
    );
}
